version: "3"
services:
  spring:
    image: 388006094889.dkr.ecr.ap-south-1.amazonaws.com/springbootdocker:VERSION
    ports:
    - 5555:8080
    networks:
    - pythonbridge
    environment:
    - MONGO_DB_HOSTNAME=mongo
    - MONGO_DB_USERNAME=devdb
    - MONGO_DB_PASSWORD=devdb@123
  mongo:
    image: mongo
    volumes:
    - mongovol:/data/db
    environment:
    - MONGO_INITDB_ROOT_USERNAME=devdb
    - MONGO_INITDB_ROOT_PASSWORD=devdb@123
    networks:
    - pythonbridge
volumes:
  mongovol:
networks:
  pythonbridge:
